### ISSUE TITLE
Commits made with non-existent user name and/or email prevent launching sessions

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#1749] opened 2022-03-22 13:14 UTC
This bug report is the result of this discourse post: https://renku.discourse.group/t/unable-to-start-session/573/2

It is worth to read the discourse post for background. But the problem was that the user was getting stuck in the `Checking session status` page in the ui forever for some reason. Without ever getting a chance to get to the screen where they can launch a session.

I have not been able to exactly replicate the problem from scratch however. But I spoke to the user and they shared their screen and it is definitely an issue. Hard reloading the page, signing in and out would not fix this. I did look at the requests sent from the browser when the user was stuck like this. There were no failed or bad requests. All responses were 200 or 30x (ie. redirects).

The only thing that helped is what I describe in the post. I.e. clicking on the `Do you want to select the branch...` link and then swapping between the different available branches until the commits load properly. If the user does not do this then they are forever stuck on the page in the screenshot below.

The user reported that they do not get stuck anymore after they fixed their local git config like below so that it matches what they have in renku.
```
git config user.name "Name"
git config user.email "Email"
```

Previously to this and in the repo history you can see that there are commits from the actual user and commits with email/name that does not really exist in Renku. This is because the users local git settings were set to something else that did not match renku.

This is the repository in question. It is public but it is on limited: https://limited.renku.ch/projects/sluis/panels-cvae

![image](https://user-images.githubusercontent.com/16360283/159489455-f0bd5acd-9596-48a2-af98-98c289a0574b.png)

**Comment by lorenzo-cavazzi** [comment] 2022-12-19 09:57
I gave it another try after some changes to how we handle the username, and I couldn't reproduce this problem anymore on the target repository. Not sure if that was fixed or not.
The UX around launching sessions has changed quite a bit in the meanwhile.

I'm closing this issue. Please feel free to open it again if this happens again or you can reproduce it.

**Closed by lorenzo-cavazzi** 2022-12-19 09:57 UTC
Labels: bug
