### ISSUE TITLE
[Environments] Stop failed/pending environments

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku-ui#787] opened 2020-02-26 13:44 UTC
## Motivation

Users often have problems when starting an environment due to various reasons:
* error in the entrypoint of the dockerfile
* unavailable resources
* registry unavailable for a newly ported project
* etc

as a result the environment is stuck in Failed or Pending state without the user being able to do something about it.

## Proposal

Add the option to stop the failed/pending environment.

## Screenshot

![unschedulable](https://user-images.githubusercontent.com/43743260/75350147-4c87b900-58a6-11ea-9d39-cac54ae97d9e.png)

**Comment by rokroskar** [comment] 2020-02-26 17:21
This is more or less a duplicate of https://github.com/SwissDataScienceCenter/renku-notebooks/issues/62

**Comment by pameladelgado** [comment] 2021-11-11 14:55
This issue became more relevant now that users can ask for storage size and that size is enforced either with a dynamically created volume or on the general emptyDir.

### Case 1
If the user ask for less storage than needed (especially when having auto-fetch LFS enabled):
- the session is not able to start
- the user does not get feedback on what happened and why
- and most importantly, it can't do anything to get out of the loop other than asking an admin to stop their session or start a session from a new commit

---------------------------------------------------------------------------

Some other scenarios can still happen:
### Case 2
When there are not enough resources in the cluster, the user should be also able to understand what happened and stop the session from being started.

**Comment by olevski** [comment] 2021-11-11 17:30
I can confirm that as far as the notebook service is concerned there are no issues sending a `DELETE` request to the `api/notebooks/servers/<server-name>` endpoint even if that server has not fully started. The notebook service actually does the exact thing any admin would do to clean things up: just runs `kubectl delete jupyterserver <server-name>`.

There is an optional `force` parameter that can be passed. This should not be used. What this does is set the termination grace period in k8s to zero (if used and set to true). By default this is set to false and the UI should not send a request with this set to `true` for this application (or for any other for that matter).

**Comment by olevski** [comment] 2021-11-11 17:31
Btw, this `DELETE` request is the same one that is sent when a session is stopped from the ui. Now the ui can enable this option even if a session has not fully started.

**Closed** 2021-12-15 15:14 UTC
Labels: QA, sessions
