### ISSUE TITLE
Tools to communicate new features

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1573] opened 2021-11-17 07:52 UTC
## Motivation

New releases of components in RenkuLab bring new features that we should tell the user about. We should have a mechanism for communicating, in a visual and appealing way, the new features.

## Mock-ups / Design

**Suggestion**
Through configuration in k8s, a banner could be shown on the landing page with a link to a RenkuLab project. Similar to this.

![image](https://user-images.githubusercontent.com/1196411/145396787-a8b9f5e4-c280-4072-9518-944c2a8b2076.png)

The RenkuLab project would explain the new features in a readme/notebook.

## Progress

- [ ] API Design (sprint-??)
- [ ] UI Implementation

**Comment by lorenzo-cavazzi** [comment] 2024-05-28 13:18
Still interesting to consider. It's actually a duplicate of #705. I'm keeping that issue open for now

**Closed by lorenzo-cavazzi** 2024-05-28 13:18 UTC
