### ISSUE TITLE
Cannot fully log out of renku

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#2594] opened 2023-06-07 14:15 UTC
Occurs on dev.renku.ch

To replicate:
- log in
- log out
- log back in (you will not be asked to enter your password/username)

This does not occur on renkulab.io. So it is a change introduced recently.

Tested on MacOS and Chrome.

**Comment by leafty** [comment] 2023-06-19 14:06
@olevski I think this is solved now, correct?

**Comment by lorenzo-cavazzi** [comment] 2023-06-21 09:29
@olevski can you confirm whether this still happens or not? I can't reproduce (or I'm trying the wrong way)

**Comment by lorenzo-cavazzi** [comment] 2023-07-11 09:50
I cannot reproduce with a test user on dev.
Perhaps that is affecting CI deployments? Anyway, I'm closing this issue but please feel free to re-open it if you can reproduce it and share the steps.

![Peek 2023-07-11 11-46](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/12d5d5b7-023f-47b8-a030-6bd53313ab8e)

**Closed by lorenzo-cavazzi** 2023-07-11 09:50 UTC
Labels: bug, status/triage
