### ISSUE TITLE
Show date/time of commit in interactive-environments page

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#853] opened 2020-03-23 09:05 UTC
## Motivation

When collaborating, I sometimes launch multiple environments on the same branch, but I cannot remember which version is which anymore.

## Proposal

Show the date/time next to the commit hash in the interactive environment display. Alternative: show it on mouse-over.

## Context

See image here: which is the newer commit? 

![image](https://user-images.githubusercontent.com/1196411/77300046-b8b2dc80-6ced-11ea-8b56-5bfb5cd3c7c8.png)

**Comment by lorenzo-cavazzi** [comment] 2020-03-23 13:45
If I correctly understand, this is for showing the commit datetime, right? If so, this requires adding it to the `renku-notebooks` API.

I initially thought it was a duplicate of #842 , but I see they are both trying to address a similar issue but it's not exactly the same thing.

**Comment by ciyer** [comment] 2020-03-24 13:03
Yes, exactly, the commit date/time. Can't we get this information from GitLab?

**Comment by lorenzo-cavazzi** [comment] 2020-03-24 13:55
We can, but we need to do a number of queries -- consider the global Environment page where we don't have any project specific information. In the worst-case scenario, we need a query for every running environment.

I would rather add the information on the backend as an annotation when the pod starts so that we don't need to invoke GitLab later

**Comment by lorenzo-cavazzi** [comment] 2020-09-29 08:52
After checking the code in renku-notebooks, I realized that adding the commit date as an annotation in the backend is not that trivial, unless we send it from the UI.
The reason is that we never interact through `git` with the repository, so accessing commits information would add an extra complexity that is very probably not needed.

I would rather start with an approach similar to what is suggested in #880 and, if it doesn't turn out to be a good solution, apply the required changes to the backend later.

**Closed** 2020-10-01 07:36 UTC
