### ISSUE TITLE
Renku is down flashes on dev.renku.ch when loading renku

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#1783] opened 2022-04-08 10:05 UTC
I am on MacOS, on Chrome 99.0.4844.84

I cannot see this on renkulab.io. But on dev.renku.ch it shows up (very briefly) but consistently. I have not checked other deployments.

https://user-images.githubusercontent.com/16360283/162414384-b2a5c22c-3aee-43e2-b1ed-8cf3f6494513.mov

**Comment by rokroskar** [comment] 2022-04-10 21:31
This happens on other deployments as well

**Comment by ciyer** [comment] 2022-04-11 11:05
This seems to be caused because the ui-server returns a 500 if the authentication token has expired.

src/routes/apis.ts:51
```
  onProxyRes: (clientRes, req: express.Request, res: express.Response) => {
    // Add CORS for sentry
    res.setHeader("Access-Control-Allow-Headers", "sentry-trace");

    const expHeader = req.get(config.auth.invalidHeaderField);
    if (expHeader != null) {
      clientRes.headers[config.auth.invalidHeaderField] = expHeader;
      if (expHeader === config.auth.invalidHeaderExpired) {
        // We return a different response to prevent side effects from caching mechanism on 30x responses
        logger.warn(`Authentication expired when trying to reach ${req.originalUrl}. Attaching auth headers.`);
        res.status(500);
        res.setHeader(config.auth.invalidHeaderField, expHeader);
        res.json({ error: "Invalid authentication tokens" });
      }
    }
  }
```

In the UI, if there is an error when trying to fetch the user, then we assume that RenkuLab is unavailable:

src/App.js:197
```
  render() {
    // Avoid rendering the application while authenticating the user
    const { user } = this.props;
    if (!user.fetched && user.fetching) {
      return (
        <section className="jumbotron-header rounded px-3 px-sm-4 py-3 py-sm-5 text-center mb-3">
          <h3 className="text-center text-primary">Checking user data</h3>
          <Loader />
        </section>
      );
    }
    else if (user.error) {
      return (<Unavailable />);
    }
```

We need to coordinate the front-end and server a bit better to do this correctly.

**Comment by lorenzo-cavazzi** [comment] 2022-04-11 11:26
This happens when the user's credential expires. We need to fix it, and this is a possible solution https://github.com/SwissDataScienceCenter/renku-ui/issues/1759#issuecomment-1080464142

I didn't mark it as high priority cause credentials expire quickly on dev (few hours iirc), while on renkulab it's a matter of days, so it's unlikely to happen often. 

P.S. this issue is a duplicate of #1759, we should close one

**Comment by ciyer** [comment] 2022-04-11 11:34
Closing in favor of #1759 which has better information.

**Closed by ciyer** 2022-04-11 11:34 UTC
