### ISSUE TITLE
Load backup session toggle in renku-ui

### ISSUE THREAD

**Issue by nperraud** [SwissDataScienceCenter/renku-ui#643] opened 2019-10-07 15:28 UTC
I believe it would be useful to have a small toggle in renku-ui to load the latest backup instead of the simple information that it will be loaded. 

This is probably important if some people work offline as they may do additional commit and then an automatic option might be very messy.

**Comment by lorenzo-cavazzi** [comment] 2019-10-08 06:52
The autosaved content is restored based on the commit you selected when you started the interactive environment. If you have unsaved work for commit A and you work offline ending up in commit B then push, when you try to start a new environment from commit B it doesn't restore any unsaved work. This means that case 2 shouldn't be problematic, the worst case is ending up with a lot of autosaved branches.

Anyway, I agree having a toggle/button that allows discarding the autosaved content would be useful.

**Comment by ciyer** [comment] 2019-10-22 07:30
@nperraud Would instructions on how to clean-up the autosave branch also be an acceptable solution for you?

I think we want to encourage people to look at the autosave branch and either merge the changes or discard them, so I would prefer a solution that is a step towards that goal.

**Comment by rokroskar** [comment] 2019-11-12 00:10
> The autosaved content is restored based on the commit you selected when you started the interactive environment.

We should make sure this is indeed the case - if @nperraud was having merge conflicts it makes me think that it was _not_ behaving as intended.

**Comment by lorenzo-cavazzi** [comment] 2019-11-14 10:29
@rokroskar I just verified and there is indeed something wrong. If I start an environment from an old commit, the autosave branch generated when I stop it references the latest commit anyway. Let me check more in depth where is the problem

**Comment by rokroskar** [comment] 2019-11-14 10:30
Great, thanks for looking into it!

**Comment by lorenzo-cavazzi** [comment] 2019-11-14 15:56
For info, a fix to that problem has been implemented here SwissDataScienceCenter/renku-notebooks#220

Thanks @nperraud for reporting, I gave it for granted that everything was working correctly but in fact it wasn't

**Comment by nperraud** [comment] 2019-11-25 21:23
Sorry for my late answer. I wasn't notified of this discution... Weird.

I did not experienced any conflict. However, I found it quite annoying to always have to go gitlab to remove backup branches... @ciyer So for me, the instructions were not the problem. @lorenzo-cavazzi I like the idea of a button, but I understand the point of @ciyer . So what about a simple functionality that allows the user to delete old backup branches that are not at the head?

**Comment by lorenzo-cavazzi** [comment] 2021-02-05 11:05
This problem will be tackled as part of #1143 .
Since that contains a few extra bits, I believe we can close this issue and refer to the other one.

**Closed by lorenzo-cavazzi** 2021-02-05 11:05 UTC
