### ISSUE TITLE
Project does not show up in dashboard when the user has been granted access to it

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#2657] opened 2023-07-13 13:29 UTC
I am not sure this is a bug or not. But when we relied on gitlab if someone gave you access to a project (that you previously had no access to) then that project would bubble up to the top of the list in the home page / dashboard.

But now with the switch to the KG we do not capture this scenario. So if someone has been granted access to a project and they go to renku then they have to manually search for this project.

A user posted about this on discourse. See here: https://renku.discourse.group/t/linking-back-from-gitlab-to-renkulab-project/846

**Comment by lorenzo-cavazzi** [comment] 2023-07-13 13:48
> But now with the switch to the KG we do not capture this scenario.

This seems unrelated to using KG. Regardless of the access level or ownership, we show the recently accessed project in the dashboard. Users need to visit the project once to have it on their dashboard

**Comment by olevski** [comment] 2023-07-14 08:29
> > But now with the switch to the KG we do not capture this scenario.

> This seems unrelated to using KG. Regardless of the access level or ownership, we show the recently accessed project in the dashboard. Users need to visit the project once to have it on their dashboard

@lorenzo-cavazzi  yes but when we depended on gitlab to list the projects, then when you were added to a project that project showed up in your dashboard/list. Now that behaviour is gone.

I think it is very unintuitive (just as the user explains in the discourse post) that when you get added to a project you then have to go digging for it in the renku search. And the renku search is not very good so you usually get a lot of hits and you have to sift through them to find the actual project you were added to.

I know this may not be easy to fix. But we should try to do something about it. And changes may need to be done perhaps on both the UI and KG side.

**Comment by lorenzo-cavazzi** [comment] 2023-07-14 09:31
Sorry this is getting a bit confusing. Let me quickly recap.

- Before introducing the new dashboard, we showed the last 4 projects the user had access to. If someone else added you to a project, you might have seen it if there were recent changes compared to your other projects. If not, you had to search for it on the projects page.
- Since the dashboard was introduced, we started using the UI server to cache the last visited projects and show those. This hasn't changed yet and KG is not involved in this process. If you have yet to visit the project you have been added to, you need to use the search page to find it.
- We plan to phase out the UI server API and switch to KG (#2599); the behavior will be similar, and we will also allow users to filter for their projects (#2522). This will probably happen within the next sprint.

Pushing projects you gained access to to the top was never considered in these scenarios. We just switched the logic from "last modified project" to "last visited project".
If your request is to show some sort of notification when users gain access to a new project, it sounds reasonable but I don't think it has to do with the dashboard.
If you believe the dashboard should behave differently, I'm happy to discuss this (perhaps the Product team is a better start), but I'm not sure there is any easy way to address the original problem through the dashboard.

**Comment by lorenzo-cavazzi** [comment] 2023-11-03 11:41
I'm closing this since the current behavior is "by design" and changing it requires planning through a pitch.
Still, I agree users should have quicker access to newly created projects. It will be easier once Renku native projects are rolled out.

**Closed by lorenzo-cavazzi** 2023-11-03 11:41 UTC
Labels: status/wontfix
