### ISSUE TITLE
Force server shutdown while pending

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku-ui#596] opened 2019-09-05 12:07 UTC
Is it possible to force stop?

![image](https://user-images.githubusercontent.com/4173925/64340372-4f37de80-cfe6-11e9-9158-d0e357d6e11c.png)
 
No action seems to be associated with the `Pending` button.

**Comment by lorenzo-cavazzi** [comment] 2019-09-05 12:28
It's currently not possible but we already have an issue for that (#499) and all the prerequisites seem to be satisfied now (SwissDataScienceCenter/renku-notebooks#205), so we will soon add the force stop action in the UI.

**Comment by lorenzo-cavazzi** [comment] 2019-09-06 14:27
Closing this since it's already tracked by #499. Please subscribe to that issue if you want to receive an update on the progress :mag: 

Btw, did you got stuck in an endless `Pending` status with some notebooks? If yes, could you please let me know how to reproduce that?

**Closed by lorenzo-cavazzi** 2019-09-06 14:27 UTC

**Comment by cchoirat** [comment] 2019-09-06 14:35
No, not endless, but taking a long time (as expected) on the wrong commit.
Hence my request for forcing shutdown.

**Comment by lorenzo-cavazzi** [comment] 2019-09-06 14:49
Ok good to know. Could you please share the link to the project and the sha of a commit having this behavior (or share it in any other way if it's not a public project)? It would be a very good test case to use while/after adding the feature :slightly_smiling_face:
