### ISSUE TITLE
Add IDs to visibility and template selectors on the New Project page

### ISSUE THREAD

**Issue by travissarles** [SwissDataScienceCenter/renku-ui#1062] opened 2020-10-06 09:03 UTC
##  Motivation

The acceptance tests need to have these IDs in order to accurately find the elements on the page and click them.
<img width="697" alt="Screen Shot 2020-10-06 at 11 02 06" src="https://user-images.githubusercontent.com/11528695/95181371-7c475980-07c3-11eb-9d07-3b4bfc3f710b.png">

**Comment by ciyer** [comment] 2020-10-08 07:32
Duplicate of #1063

**Closed by ciyer** 2020-10-08 07:32 UTC
