### ISSUE TITLE
Use ui-server to poll notebook session state

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1264] opened 2021-03-09 09:37 UTC
# Description

Use the ui-server to poll for changes in notebook session state and pass them to the UI asynchronously. The information provided to the UI should also include the disk, CPU, and memory usage from the jupyterServer custom resource.

This information will be used in the UI during launch (since a session may not start if disk space limits are reached) and on running sessions.

**Comment by lorenzo-cavazzi** [comment] 2022-11-11 11:07
This is mostly a duplicate of #2016 . Closing this since the other contains more details

**Closed by lorenzo-cavazzi** 2022-11-11 11:07 UTC
Labels: ui-server
