### ISSUE TITLE
New project not added to list of projects

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku-ui#444] opened 2019-04-26 13:59 UTC
When I create a new project:
![image](https://user-images.githubusercontent.com/4173925/56812817-f4be9280-683b-11e9-96e4-ccf004d96860.png)
it is not automatically listed in the list of new projects:
![image](https://user-images.githubusercontent.com/4173925/56812878-1ae43280-683c-11e9-86c1-cc64eb61b2f7.png)
I have to refresh the page:
![image](https://user-images.githubusercontent.com/4173925/56812893-27688b00-683c-11e9-8032-5b6977e22559.png)

**Comment by lorenzo-cavazzi** [comment] 2019-04-26 15:35
Thanks for the feedback and the detailed description. 
This is already in the bug-list and is going to be fixed. Closing only because it's a duplicate of #408.

**Closed by lorenzo-cavazzi** 2019-04-26 15:35 UTC
